"""add batches and batch_id to members

Revision ID: 3e86cef2291e
Revises: 10f41fa670db
Create Date: 2026-08-08 15:33:46.336350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e86cef2291e'
down_revision: Union[str, Sequence[str], None] = '10f41fa670db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('batch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'members', 'batches', ['batch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.drop_column('members', 'batch_id')
    # ### end Alembic commands ###
